# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 955be1e4da726ebda589048e7268df1db0c213365bb1bfe28243e54ebcb6ebd81b869cf868aa29e71ea45063199feb0a552a7b187171c825d6d1abf3b8af8f96

test:
  secret_key_base: 7809d9dbc2f74d215a0234c0414ca709f051c583d1327a2325fdfdb6e111e31d88bed134e0200864d4224c8a650197f9f691efdf7d88c2a18287fe9323d6102d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
